2024-11-04 14:31:52.893 - INFO    - MainThread - client.py:204 [connectAsync] - Connecting to 127.0.0.1:7497 with clientId 53963...
2024-11-04 14:31:52.895 - INFO    - MainThread - client.py:212 [connectAsync] - Connected
2024-11-04 14:31:52.901 - INFO    - MainThread - client.py:341 [_onSocketHasData] - Logged on to server version 178
2024-11-04 14:31:52.918 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2104, reqId -1: Market data farm connection is OK:hfarm
2024-11-04 14:31:52.919 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfuture.il
2024-11-04 14:31:52.919 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2104, reqId -1: Market data farm connection is OK:cashfarm
2024-11-04 14:31:52.923 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfuture
2024-11-04 14:31:52.924 - INFO    - MainThread - client.py:218 [connectAsync] - API connection ready
2024-11-04 14:31:52.925 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfarm.nj
2024-11-04 14:31:52.926 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfarm
2024-11-04 14:31:52.926 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:euhmds
2024-11-04 14:31:52.927 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:apachmds
2024-11-04 14:31:52.927 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:fundfarm
2024-11-04 14:31:52.927 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:ushmds
2024-11-04 14:31:52.928 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2158, reqId -1: Sec-def data farm connection is OK:secdefhk
2024-11-04 14:31:53.362 - INFO    - MainThread - ibstore_insync.py:2754 [connectAsync] - Synchronization complete
2024-11-04 14:31:58.096 - ERROR   - MainThread - wrapper.py:1219 [error] - Error 162, reqId 6: Historical Market Data Service error message:Unknown contract, contract: Contract(secType='STK', conId=208813720, symbol='GOOG', exchange='SMART', primaryExchange='ISLAND', currency='USD', localSymbol='GOOG', tradingClass='NMS')
