2024-10-31 20:06:39.233 - INFO    - MainThread - client.py:204 [connectAsync] - Connecting to 127.0.0.1:7497 with clientId 34305...
2024-10-31 20:06:39.235 - INFO    - MainThread - client.py:212 [connectAsync] - Connected
2024-10-31 20:06:39.242 - INFO    - MainThread - client.py:341 [_onSocketHasData] - Logged on to server version 178
2024-10-31 20:06:39.251 - ERROR   - MainThread - decoder.py:189 [handler] - Error for managedAccounts:
Traceback (most recent call last):
  File "E:\gitcode\backtrader\backtrader\stores\ibstores\decoder.py", line 187, in handler
    method(*args)
    ~~~~~~^^^^^^^
  File "E:\gitcode\backtrader\backtrader\stores\ibstores\wrapper.py", line 291, in managedAccounts
    self.ib.managedAccounts(accountsList)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: IBStoreInsync.managedAccounts() takes 1 positional argument but 2 were given
2024-10-31 20:06:39.256 - INFO    - MainThread - client.py:218 [connectAsync] - API connection ready
2024-10-31 20:06:39.257 - INFO    - MainThread - wrapper.py:1204 [error] - Warning 2104, reqId -1: Market data farm connection is OK:hfarm
2024-10-31 20:06:39.257 - INFO    - MainThread - wrapper.py:1204 [error] - Warning 2104, reqId -1: Market data farm connection is OK:cashfarm
2024-10-31 20:06:39.258 - INFO    - MainThread - wrapper.py:1204 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfarm.nj
2024-10-31 20:06:39.258 - INFO    - MainThread - wrapper.py:1204 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfarm
2024-10-31 20:06:39.259 - INFO    - MainThread - wrapper.py:1204 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:euhmds
2024-10-31 20:06:39.259 - INFO    - MainThread - wrapper.py:1204 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:apachmds
2024-10-31 20:06:39.259 - INFO    - MainThread - wrapper.py:1204 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:fundfarm
2024-10-31 20:06:39.259 - INFO    - MainThread - wrapper.py:1204 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:ushmds
2024-10-31 20:06:39.260 - INFO    - MainThread - wrapper.py:1204 [error] - Warning 2158, reqId -1: Sec-def data farm connection is OK:secdefhk
2024-10-31 20:06:39.469 - INFO    - MainThread - ibstore_insync.py:2722 [connectAsync] - Synchronization complete
2024-10-31 20:06:43.172 - ERROR   - MainThread - decoder.py:200 [interpret] - Error handling fields: ['10', '3', 'EUR', 'CASH', '', '0', '', 'IDEALPRO', 'USD', 'EUR.USD', 'EUR.USD', 'EUR.USD', '12087792', '0.00005', '', 'ACTIVETIM,AD,ADJUST,ALERT,ALGO,ALLOC,AVGCOST,BASKET,CASHQTY,COND,CONDORDER,DAY,DEACT,DEACTDIS,DEACTEOD,GAT,GTC,GTD,GTT,HID,IOC,LIT,LMT,MIT,MKT,NONALGO,OCA,REL,RELPCTOFS,SCALE,SCALERST,STP,STPLMT,TRAIL,TRAILLIT,TRAILLMT,TRAILMIT,WHATIF', 'IDEALPRO', '1', '0', 'European Monetary Union Euro', '', '', '', '', '', 'US/Eastern', '20241029:1715-20241030:1700;20241030:1715-20241031:1700;20241031:1715-20241101:1700;20241102:CLOSED;20241103:1715-20241104:1700;20241104:1715-20241105:1700', '20241029:1715-20241030:1700;20241030:1715-20241031:1700;20241031:1715-20241101:1700;20241102:CLOSED;20241103:1715-20241104:1700;20241104:1715-20241105:1700', '', '', '0', '4', '', '', '3188', '', '', '0.01', '0.01', '0.01']
Traceback (most recent call last):
  File "E:\gitcode\backtrader\backtrader\stores\ibstores\decoder.py", line 198, in interpret
    handler(fields)
    ~~~~~~~^^^^^^^^
  File "E:\gitcode\backtrader\backtrader\stores\ibstores\decoder.py", line 338, in contractDetails
    self.wrapper.contractDetails(int(reqId), cd)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "E:\gitcode\backtrader\backtrader\stores\ibstores\wrapper.py", line 588, in contractDetails
    self.ib.contractDetails(reqId, contractDetails)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\gitcode\backtrader\backtrader\stores\ibstore_insync.py", line 487, in contractDetails
    self.qs[reqId].put(contractDetails)
    ~~~~~~~^^^^^^^
KeyError: 3
2024-10-31 20:06:43.174 - ERROR   - MainThread - decoder.py:189 [handler] - Error for contractDetailsEnd:
Traceback (most recent call last):
  File "E:\gitcode\backtrader\backtrader\stores\ibstores\decoder.py", line 187, in handler
    method(*args)
    ~~~~~~^^^^^^^
  File "E:\gitcode\backtrader\backtrader\stores\ibstores\wrapper.py", line 594, in contractDetailsEnd
    self.ib.contractDetailsEnd(reqId)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "E:\gitcode\backtrader\backtrader\stores\ibstore_insync.py", line 481, in contractDetailsEnd
    self.cancelQueue(self.qs[reqId], True)
                     ~~~~~~~^^^^^^^
KeyError: 3
2024-10-31 20:39:45.773 - ERROR   - MainThread - wrapper.py:1206 [error] - Error 1100, reqId -1: Connectivity between IBKR and Trader Workstation has been lost.
2024-10-31 20:39:51.278 - ERROR   - MainThread - wrapper.py:1206 [error] - Error 1100, reqId -1: Connectivity between IBKR and Trader Workstation has been lost.
2024-10-31 20:39:54.283 - ERROR   - MainThread - wrapper.py:1206 [error] - Error 1100, reqId -1: Connectivity between IBKR and Trader Workstation has been lost.
2024-10-31 20:40:06.859 - ERROR   - MainThread - wrapper.py:1206 [error] - Error 1100, reqId -1: Connectivity between IBKR and Trader Workstation has been lost.
2024-10-31 20:40:15.163 - ERROR   - MainThread - wrapper.py:1206 [error] - Error 1100, reqId -1: Connectivity between IBKR and Trader Workstation has been lost.
2024-10-31 20:40:25.035 - ERROR   - MainThread - wrapper.py:1206 [error] - Error 1100, reqId -1: Connectivity between IBKR and Trader Workstation has been lost.
2024-10-31 20:40:25.554 - ERROR   - MainThread - wrapper.py:1206 [error] - Error 1100, reqId -1: Connectivity between IBKR and Trader Workstation has been lost.
2024-10-31 20:40:39.382 - ERROR   - MainThread - wrapper.py:1206 [error] - Error 1100, reqId -1: Connectivity between IBKR and Trader Workstation has been lost.
2024-10-31 20:41:01.290 - ERROR   - MainThread - wrapper.py:1206 [error] - Error 1100, reqId -1: Connectivity between IBKR and Trader Workstation has been lost.
2024-10-31 20:41:36.777 - ERROR   - MainThread - wrapper.py:1206 [error] - Error 1100, reqId -1: Connectivity between IBKR and Trader Workstation has been lost.
2024-10-31 20:42:08.014 - ERROR   - MainThread - wrapper.py:1206 [error] - Error 1102, reqId -1: Connectivity between IBKR and Trader Workstation has been restored - data maintained. All data farms are connected: hfarm; cashfarm; usfarm.nj; usfarm; euhmds; apachmds; fundfarm; ushmds; secdefhk.
2024-10-31 20:42:08.132 - INFO    - MainThread - wrapper.py:1204 [error] - Warning 2105, reqId -1: HMDS data farm connection is broken:apachmds
2024-10-31 20:42:08.482 - INFO    - MainThread - wrapper.py:1204 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:apachmds
