2024-11-04 14:18:01.683 - INFO    - MainThread - client.py:204 [connectAsync] - Connecting to 127.0.0.1:7497 with clientId 45198...
2024-11-04 14:18:01.685 - INFO    - MainThread - client.py:212 [connectAsync] - Connected
2024-11-04 14:18:01.690 - INFO    - MainThread - client.py:341 [_onSocketHasData] - Logged on to server version 178
2024-11-04 14:18:01.706 - INFO    - MainThread - client.py:218 [connectAsync] - API connection ready
2024-11-04 14:18:01.708 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2104, reqId -1: Market data farm connection is OK:hfarm
2024-11-04 14:18:01.708 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfuture.il
2024-11-04 14:18:01.711 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2104, reqId -1: Market data farm connection is OK:cashfarm
2024-11-04 14:18:01.711 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfuture
2024-11-04 14:18:01.712 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfarm.nj
2024-11-04 14:18:01.712 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfarm
2024-11-04 14:18:01.713 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:euhmds
2024-11-04 14:18:01.713 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:apachmds
2024-11-04 14:18:01.713 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:fundfarm
2024-11-04 14:18:01.714 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:ushmds
2024-11-04 14:18:01.714 - INFO    - MainThread - wrapper.py:1217 [error] - Warning 2158, reqId -1: Sec-def data farm connection is OK:secdefhk
2024-11-04 14:18:02.163 - INFO    - MainThread - ibstore_insync.py:2754 [connectAsync] - Synchronization complete
2024-11-04 14:18:07.032 - ERROR   - MainThread - wrapper.py:1219 [error] - Error 321, reqId 6: Error validating request.-'bK' : cause - End date not supported with live updates, contract: Contract(secType='STK', conId=208813720, symbol='GOOG', exchange='SMART', primaryExchange='ISLAND', currency='USD', localSymbol='GOOG', tradingClass='NMS')
