2024-11-01 13:18:33.591 - INFO    - MainThread - client.py:204 [connectAsync] - Connecting to 127.0.0.1:7497 with clientId 6671...
2024-11-01 13:18:33.593 - INFO    - MainThread - client.py:212 [connectAsync] - Connected
2024-11-01 13:18:33.597 - INFO    - MainThread - client.py:341 [_onSocketHasData] - Logged on to server version 178
2024-11-01 13:18:33.609 - ERROR   - MainThread - decoder.py:189 [handler] - Error for managedAccounts:
Traceback (most recent call last):
  File "E:\gitcode\backtrader\backtrader\stores\ibstores\decoder.py", line 187, in handler
    method(*args)
    ~~~~~~^^^^^^^
  File "E:\gitcode\backtrader\backtrader\stores\ibstores\wrapper.py", line 292, in managedAccounts
    self.ib.managedAccounts(accountsList)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: IBStoreInsync.managedAccounts() takes 1 positional argument but 2 were given
2024-11-01 13:18:33.613 - INFO    - MainThread - client.py:218 [connectAsync] - API connection ready
2024-11-01 13:18:33.613 - INFO    - MainThread - ibstore_insync.py:1167 [disconnect] - Disconnecting from 127.0.0.1:7497, 32 B sent in 2 messages, 75 B received in 3 messages, session time 23.0 ms.
2024-11-01 13:18:33.613 - INFO    - MainThread - client.py:230 [disconnect] - Disconnecting
2024-11-01 13:18:33.614 - INFO    - MainThread - wrapper.py:1211 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfuture.il
2024-11-01 13:18:33.615 - INFO    - MainThread - client.py:368 [_onSocketDisconnected] - Disconnected.
