2024-10-31 12:29:19.541 - INFO    - MainThread - client.py:204 [connectAsync] - Connecting to 127.0.0.1:7497 with clientId 38168...
2024-10-31 12:29:19.543 - INFO    - MainThread - client.py:212 [connectAsync] - Connected
2024-10-31 12:29:19.546 - INFO    - MainThread - client.py:341 [_onSocketHasData] - Logged on to server version 176
2024-10-31 12:29:19.553 - ERROR   - MainThread - decoder.py:189 [handler] - Error for managedAccounts:
Traceback (most recent call last):
  File "c:\Users\felin\AppData\Local\Programs\Python\Python313\Lib\site-packages\ib_insync\decoder.py", line 187, in handler
    method(*args)
    ~~~~~~^^^^^^^
  File "c:\Users\felin\AppData\Local\Programs\Python\Python313\Lib\site-packages\ib_insync\wrapper.py", line 241, in managedAccounts
    self.ib.managedAccounts(accountsList)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: IBStoreInsync.managedAccounts() takes 1 positional argument but 2 were given
2024-10-31 12:29:19.556 - INFO    - MainThread - client.py:218 [connectAsync] - API connection ready
2024-10-31 12:29:19.557 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2104, reqId -1: Market data farm connection is OK:hfarm
2024-10-31 12:29:19.558 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2104, reqId -1: Market data farm connection is OK:cashfarm
2024-10-31 12:29:19.558 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfarm.nj
2024-10-31 12:29:19.558 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfarm
2024-10-31 12:29:19.559 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:euhmds
2024-10-31 12:29:19.559 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:apachmds
2024-10-31 12:29:19.559 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:fundfarm
2024-10-31 12:29:19.560 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:ushmds
2024-10-31 12:29:19.560 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2158, reqId -1: Sec-def data farm connection is OK:secdefhk
2024-10-31 12:29:19.877 - INFO    - MainThread - ibstore_insync.py:2710 [connectAsync] - Synchronization complete
2024-10-31 12:29:22.010 - ERROR   - MainThread - decoder.py:200 [interpret] - Error handling fields: ['10', '3', 'EUR', 'CASH', '', '0', '', 'IDEALPRO', 'USD', 'EUR.USD', 'EUR.USD', 'EUR.USD', '12087792', '0.00005', '', 'ACTIVETIM,AD,ADJUST,ALERT,ALGO,ALLOC,AVGCOST,BASKET,CASHQTY,COND,CONDORDER,DAY,DEACT,DEACTDIS,DEACTEOD,GAT,GTC,GTD,GTT,HID,IOC,LIT,LMT,MIT,MKT,NONALGO,OCA,REL,RELPCTOFS,SCALE,SCALERST,STP,STPLMT,TRAIL,TRAILLIT,TRAILLMT,TRAILMIT,WHATIF', 'IDEALPRO', '1', '0', 'European Monetary Union Euro', '', '', '', '', '', 'US/Eastern', '20241029:1715-20241030:1700;20241030:1715-20241031:1700;20241031:1715-20241101:1700;20241102:CLOSED;20241103:1715-20241104:1700;20241104:1715-20241105:1700', '20241029:1715-20241030:1700;20241030:1715-20241031:1700;20241031:1715-20241101:1700;20241102:CLOSED;20241103:1715-20241104:1700;20241104:1715-20241105:1700', '', '', '0', '4', '', '', '3188', '', '', '0.01', '0.01', '0.01']
Traceback (most recent call last):
  File "c:\Users\felin\AppData\Local\Programs\Python\Python313\Lib\site-packages\ib_insync\decoder.py", line 198, in interpret
    handler(fields)
    ~~~~~~~^^^^^^^^
  File "c:\Users\felin\AppData\Local\Programs\Python\Python313\Lib\site-packages\ib_insync\decoder.py", line 336, in contractDetails
    self.wrapper.contractDetails(int(reqId), cd)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "c:\Users\felin\AppData\Local\Programs\Python\Python313\Lib\site-packages\ib_insync\wrapper.py", line 537, in contractDetails
    self.ib.contractDetails(reqId, contractDetails)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\gitcode\backtrader\backtrader\stores\ibstore_insync.py", line 476, in contractDetails
    self.qs[reqId].put(contractDetails)
    ~~~~~~~^^^^^^^
KeyError: 3
2024-10-31 12:29:22.012 - ERROR   - MainThread - decoder.py:189 [handler] - Error for contractDetailsEnd:
Traceback (most recent call last):
  File "c:\Users\felin\AppData\Local\Programs\Python\Python313\Lib\site-packages\ib_insync\decoder.py", line 187, in handler
    method(*args)
    ~~~~~~^^^^^^^
  File "c:\Users\felin\AppData\Local\Programs\Python\Python313\Lib\site-packages\ib_insync\wrapper.py", line 543, in contractDetailsEnd
    self.ib.contractDetailsEnd(reqId)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "E:\gitcode\backtrader\backtrader\stores\ibstore_insync.py", line 471, in contractDetailsEnd
    self.cancelQueue(self.qs[reqId], True)
                     ~~~~~~~^^^^^^^
KeyError: 3
2024-10-31 12:29:42.778 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfuture.il
2024-10-31 12:29:42.802 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfuture
2024-10-31 12:33:29.161 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2108, reqId -1: Market data farm connection is inactive but should be available upon demand.usfuture.il
2024-10-31 12:33:29.162 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2108, reqId -1: Market data farm connection is inactive but should be available upon demand.usfuture.il
2024-10-31 12:33:29.163 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2108, reqId -1: Market data farm connection is inactive but should be available upon demand.usfuture
2024-10-31 12:33:29.164 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2108, reqId -1: Market data farm connection is inactive but should be available upon demand.usfuture
2024-10-31 13:03:32.673 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2105, reqId -1: HMDS data farm connection is broken:euhmds
2024-10-31 13:03:38.719 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:euhmds
